// The JS port against the Python reference (test/golden, generated by
// tools/python-reference.py from the same fixtures).

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { I, GOLDEN, shotFixtures, normalize } from "./load.mjs";

function fullMetrics(rows, shot) {
  const ann = shot.annotations || {};
  const toN = (v) => (typeof v === "number" ? v : null);
  const m = I.coreMetrics(rows, toN(ann.actualDoseWeight), toN(ann.actualYield));
  const resistance = I.puckResistance(rows);
  return { ...m, puck_resistance: resistance, channeling: I.channeling(rows, m, resistance), profile_compliance: I.profileCompliance(rows) };
}

for (const { file, why, shot } of shotFixtures()) {
  const golden = JSON.parse(fs.readFileSync(path.join(GOLDEN, file), "utf8"));

  test(`parity ${file} (${why})`, async (t) => {
    const rows = I.rowsFromShot(shot);

    await t.test("rows", () => {
      assert.deepEqual(normalize(rows), normalize(golden.rows));
    });

    const metrics = fullMetrics(rows, shot);
    await t.test("metrics and diagnostics", () => {
      const expected = { ...golden.metrics };
      delete expected.metrics_version;
      assert.deepEqual(normalize(metrics), normalize(expected));
    });

    await t.test("curve shape", () => {
      assert.deepEqual(normalize(I.curveShape(rows, metrics)), normalize(golden.curve_shape));
    });

    await t.test("downsampled curve (60, 400)", () => {
      const keep = [metrics.t_peak, metrics.t_max_pressure_global];
      assert.deepEqual(normalize(I.downsampleCurve(rows, 60, keep)), normalize(golden.curve_60));
      assert.deepEqual(normalize(I.downsampleCurve(rows, 400, keep)), normalize(golden.curve_400));
    });
  });
}

test("pyRound matches Python's round() on ties and near-ties", () => {
  // Values chosen so that half-up and half-even disagree, or the binary value
  // sits just below/above the decimal tie.
  // Expected values are Python 3.12 output.
  const cases = [
    [0.125, 2, 0.12], [0.375, 2, 0.38], [2.5, 0, 2], [3.5, 0, 4], [-2.5, 0, -2],
    [2.675, 2, 2.67], [1.005, 2, 1], [0.0625, 3, 0.062], [1.45, 1, 1.4], [1.55, 1, 1.6],
    [123.4565, 3, 123.457], [9.995, 2, 9.99], [0.5, 0, 0], [1.5, 0, 2], [-0.0005, 3, -0.001],
  ];
  for (const [x, n, expected] of cases) assert.equal(I.pyRound(x, n), expected, `round(${x}, ${n})`);
  assert.equal(I.pyFixed(-0.001, 2), "-0.00");
  assert.equal(I.pyFixed(0.125, 2), "0.12");
});

// Independent exact reference: Python's round() on the exact decimal
// expansion of the double, ties to even.
function exactRound(x, n) {
  const e = Math.abs(x).toFixed(100);
  const dot = e.indexOf(".");
  const kept = (e.slice(0, dot) + e.slice(dot + 1, dot + 1 + n));
  const rest = e.slice(dot + 1 + n);
  let k = BigInt(kept);
  if (rest[0] > "5" || (rest[0] === "5" && (/[1-9]/.test(rest.slice(1)) || k % 2n === 1n))) k += 1n;
  const v = Number(k) / 10 ** n;
  return x < 0 ? -v : v;
}

test("pyRound's fast path agrees with the exact reference (200,000 values)", () => {
  let seed = 42;
  const rand = () => ((seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648);
  for (let i = 0; i < 200000; i++) {
    const n = Math.floor(rand() * 4);
    // Mix of random values and values right at decimal ties.
    const x = i % 3 === 0
      ? (Math.floor(rand() * 20000) + 0.5) / 10 ** n * (rand() < 0.5 ? -1 : 1)
      : (rand() - 0.5) * 10 ** (rand() * 4);
    const got = I.pyRound(x, n);
    const want = exactRound(x, n);
    if (!(got === want || (got === 0 && want === 0))) assert.fail(`round(${x}, ${n}) = ${got}, expected ${want}`);
  }
});
